### ISSUE TITLE
wrong Code

### ISSUE THREAD

**Issue by sadi2003q** [Aaban-Saad/CSE225L-Project-CENACE-using-Js#1]
Unnecessary code, Waste of time and brain power, don't need anything, just need a good nap and a sweet dream to become a Google. just leave coding and sleep into the bed😤

**Comment by Aaban-Saad** [comment]
Yeah, absolutely!

**Comment by Aaban-Saad** [comment]
> Unnecessary code, Waste of time and brain power, don't need anything, just need a good nap and a sweet dream to become a Google. just leave coding and sleep into the bed😤

Yeah, absolutely!
